site: TruongNguyen.io

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /projects/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-compress-images

paginate: 10
paginate_path: "/blog/page:num/"

gallery_types:
  carousel: Carousel
  grid: Grid
grid_columns:
  two: Two
  three: Three
  four: Four

compress_images:
  images_path: "/images/posts/*.{gif,png,jpg,jpeg,svg}"

imageoptim:
  svgo: false

exclude:
  - vendor
  - _compress_images_cache.yml