# For Facebook Instant
title: truongnguyen.io
description: "What I've been up to including my thoughts, travels, coding and photography."
# change it to your site address.
# depending on your configuration, you might have to add a / after the address.
url: https://truongnguyen.io
default_bg: /images/logo.png
owner:
  name:           Truong Nguyen
  avatar:         /images/favicon.png
# end of Facebook Instant

site: TruongNguyen.io

collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /blog/:slug/
  projects:
    output: true
    permalink: /projects/:slug/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-compress-images
  - jekyll-figure

paginate: 10
paginate_path: "/blog/page:num/"

gallery_types:
  carousel: Carousel
  grid: Grid
grid_columns:
  two: Two
  three: Three
  four: Four

compress_images:
  images_path: "/images/posts/*.{gif,png,jpg,jpeg,svg}"

imageoptim:
  svgo: false

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: truongnguyenio

exclude:
  - config.codekit3
  - vendor
  - _compress_images_cache.yml

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]