backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "images/posts"

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featured_image", widget: "image", default: "/images/og-image.jpg"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Link", name: "permalink", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Publish?", name: "published", widget: "boolean", default: true, required: false}
      - {label: "Enable comments?", name: "comments", widget: "boolean", default: true, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Layout"
        name: "layout"
        widget: "select"
        default: "page"
        options: 
          - { label: "Default", value: "page" }
          - { label: "Blank", value: "blank" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featured_image", widget: "image", default: "/images/og-image.jpg"}
      - {label: "Link", name: "permalink", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Publish?", name: "published", widget: "boolean", default: true, required: false}
      - {label: "Enable comments?", name: "comments", widget: "boolean", default: false, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
